Name include 'Max' and rating as '*'
Hunk13/scrap_movies pull request #1
Opened 2017-05-29 08:52 UTC by Hunk13

2017-05-29 09:41 UTC, zverok requested changes

2017-05-29 09:41 UTC, zverok commented on main.rb
> +  puts output_movie[1] + ' | ' + ('*' * ('%.1f' % ((output_movie[7].to_f - 8) * 10)).to_i)
а зачем трюк с `'%.1f' % `?..

2017-05-29 09:41 UTC, zverok commented on main.rb
> +  file
Можно не использовать эту сложную проверку и вывод сообщения, а использовать просто оператор `||`

2017-05-29 09:41 UTC, zverok commented on main.rb
> +  file
А  как мы попадаем в эту ветку, в каком случае?

2017-05-29 09:41 UTC, zverok commented on main.rb
> +elsif File.exist?(ARGV[0]) ? file = ARGV[0] : abort("File '#{ARGV[0]}' not exist.")
А если использован дефолтный файл, но он тоже несщуествует?

2017-05-29 09:41 UTC, zverok commented on main.rb
> +end
Учитывая, что задание — просто напечатать что-то для заданных строчек, по-моему это можно было сделать за один проход по файлу, не?

2017-05-29 09:41 UTC, zverok commented on main.rb
> +open_file = File.open(file, 'r')
`File.each_line` и не плодить переменных :)

2017-05-29 18:42 UTC, zverok requested changes

2017-05-29 18:42 UTC, zverok commented on main.rb
> +end
Не. Тут достаточно двух строчек. Логику надо просто разделить:
1. имя файла — из командной строки или дефолтное
2. выйти если файл не существует.

Вот реально должно быть эти две строчки и всё :)

2017-05-29 18:42 UTC, zverok commented on main.rb
> +end
Ага, тут норм.

2017-05-29 20:53 UTC, Hunk13 commented on main.rb
> +end
Да, после этой подсказки все получилось.

2017-05-29 20:56 UTC, Hunk13 commented on main.rb
> +abort('File not exist.') unless File.exist?(file)
Вот в таком виде вроде все должно быть нормально.

2017-05-30 09:27 UTC, zverok approved these changes
Воо!

2017-05-30 09:34 UTC, merged