Oop inheritance
Hunk13/scrap_movies pull request #5
Opened 2017-06-20 12:08 UTC by Hunk13

2017-06-20 19:07 UTC, zverok requested changes

2017-06-20 19:07 UTC, zverok commented on movie.rb
> +  def new_movie(movie_collection, movie)
1. `new_movie` — не очень хорошее название (потому что похоже на название одного из наших классов, такое ощущение что оно только `NewMovie` создавать)
2. очень странно, что это instance method. То есть получается, чтобы получить `NewMovie`, мы сначала создаём экземпляр `Movie`, потом из него `NewMovie`, а сам `Movie` забываем. Лучше class method

2017-06-20 19:07 UTC, zverok commented on netflix.rb
> +    filter(title: input_movie_name).select { |movie| movie.rating * rand }.last.movie_price
а если не нашёлся фильм?..

2017-06-20 19:07 UTC, zverok commented on spec/movie_collection_spec.rb
> +  end
с гемом `rspec-its`:
```ruby
its(:all) { is_expected.to be_an(Array).and have_attributes(count: 250).and all be_a Movie }
```

2017-06-20 19:07 UTC, zverok commented on spec/movie_collection_spec.rb
> +      expect(subject.sort_by(:length)).to be_an(Array)
И что это тестирует? :)
Этот тест запросто пройдёт вот такая реализация:
```ruby
def sort_by(*)
  []
end
```
;)

2017-06-20 19:07 UTC, zverok commented on spec/movie_collection_spec.rb
> +    end
Аналогично.

2017-06-20 19:07 UTC, zverok commented on spec/movie_collection_spec.rb
> +  end
...и аналогично.

2017-06-20 19:07 UTC, zverok commented on spec/movie_spec.rb
> +  end
Эти три теста лучше бы структурировать так:
```ruby
describe '#genre?' do # что описываем
  subject { movie.genre?(genre) } # предмет теста

  # как оно работает в разных _контекстах_
  context 'present' do
    let(:genre) { 'Crime' }
    it { is_expected.to be_truthy }
  end

  context 'absent' do
    let(:genre) { 'Action' }
    it { is_expected.to be_falsey }
  end

  context 'non-existing' do
    let(:genre) { 'Criminalis' }
    it { expect { subject }.to raise_error..... }
  end
end
```

Понимаешь логику, да?..

2017-06-20 19:07 UTC, zverok commented on spec/movie_spec.rb
> +  end
...и тут тоже учесть все комменты выше. И хорошо бы тестировать класс фильма сам по себе, а не `.all.first`

2017-06-20 19:07 UTC, zverok commented on spec/netflix_spec.rb
> +    expect(subject.money).to eq(10)
Тут бы нам `expect { ... }.to change ` пригодился.

2017-06-20 19:07 UTC, zverok commented on spec/netflix_spec.rb
> +  end
Все тесты `show` лучше сгруппировать в `describe '#show'`, и описать через несколько _контекстов_. Каждый _тест_ в идеале — одно выражение (один матчер или несколько, объединённых через `and`, тестируемый метод описан в `subject`, предусловия (столько-то уплачено) — в `before`.

2017-06-20 19:07 UTC, zverok commented on spec/netflix_spec.rb
> +  end
Относится ко всем спекам, дальше их не комментирую)

2017-06-20 19:07 UTC, zverok commented on theatre.rb
> +end
Тут неплохо, компактно получилось.

2017-06-22 21:33 UTC, zverok requested changes

2017-06-22 21:33 UTC, zverok commented on movie.rb
> +  def self.create_movies(movie_collection, movie)
Мелочь, конешн, но: лучше параметр как-то по-другому обозвать, чтобы не путаться, типа `movie_data`, или `source` или как-то так (чтобы было понятно, что это ещё НЕ готовый фильм)

2017-06-22 21:33 UTC, zverok commented on movie.rb
> +    end
На самом деле тут будет эффективнее `params.all?`, кстати ;)

2017-06-22 21:33 UTC, zverok commented on netflix.rb
> +# class Netflix child from MovieCollection
Что нам говорит этот коммент, чего непонятно из кода?..

2017-06-22 21:33 UTC, zverok commented on netflix.rb
> +    mov = filter(title: input_movie_name).select { |movie| movie.rating * rand }.last
а что здесь делает `select`? как он предположительно должен работать???

2017-06-22 21:33 UTC, zverok commented on new_movie.rb
> +# Class NewMowie
Здесь (и везде) — ну зачем это? Или нормальный документирующий коммент, или никаково не надо

2017-06-22 21:33 UTC, zverok commented on new_movie.rb
> +  end
Серьёзно? `Time.now.year` же...

2017-06-22 21:33 UTC, zverok commented on spec/movie_collection_spec.rb
> +      it { is_expected.to be_an(Array) }
Да ладно :)

2017-06-22 21:33 UTC, zverok commented on spec/movie_collection_spec.rb
> +    end
Не, это не тест ничего. Его всё ещё проходит метод выглядящий так:
```ruby
def stats(*); [] end
```

Идея теста в том чтобы он _падал_ при любой реализации кроме правильной.

2017-06-22 21:33 UTC, zverok commented on spec/movie_spec.rb
> +    subject { movie }
Нет необходимости в этой строке, он у тебя и так уже как дефолтный subject определён.

2017-06-22 21:33 UTC, zverok commented on spec/movie_spec.rb
> +    end
Мммм... 
а) `its(:actors) { are_expected.to ... }`
б) тест-то слабоват. его пройдёт довольно тупая реализация (как и в примерах выше)

2017-06-22 21:33 UTC, zverok commented on spec/movie_spec.rb
> +      expect(subject.movie_price).to eq(3)
нда? у дефолтного фильма есть цена?

2017-06-22 21:33 UTC, zverok commented on spec/movie_spec.rb
> +  subject(:movie) { collection.all.first }
по-хорошему, тест фильма не должен думать о коллекции. то есть лучше бы он тут сам создавался из каких-то данных, и только этот, из данных, и тестировался.

2017-06-22 21:33 UTC, zverok commented on spec/netflix_spec.rb
> +  subject(:collection) { described_class.new('movies.txt') }
я бы сказал `subject(:netflix)`, чиста аккуратности ради, не?

2017-06-22 21:33 UTC, zverok commented on spec/netflix_spec.rb
> +          .and change(collection, :money).by(0)
я бы сказал `and not_change` (см. `define_negated_matcher`), более как-то лучше смысл отображает.

2017-06-22 21:33 UTC, zverok commented on spec/netflix_spec.rb
> +      let(:title) { { title: 'The Terminator' } }
Оно ж одинаковое для всех примеров, зачем повторяется?..

2017-06-22 21:33 UTC, zverok commented on spec/netflix_spec.rb
> +      it { expect(subject).to be_a_kind_of(Numeric) }
Я знаю, какой метод пройдёт этот тест! Вот такой:
```ruby
def how_much?
  -1_000_000_000.23456789
end
```
или, может, такой?..
```ruby
def how_much?
  rand(-42..42)
end
```
Я молодец?..

2017-06-22 21:33 UTC, zverok commented on spec/theatre_spec.rb
> +      }
а) слишком либеральный тест, много что его пройдёт...
б) а другие существующие периоды?

2017-06-22 21:33 UTC, zverok commented on spec/theatre_spec.rb
> +    end
опять же, хорошо бы несколько вариантов:
* фильм из такого периода
* фильм из другого периода
* фильм который существует но никогда не показывается
* фильм которого не существует

2017-06-29 10:25 UTC, zverok reviewed
Уже почти отлично.

2017-06-29 10:25 UTC, zverok commented on movie.rb
> +  def self.movie_data(movie, movie_collection = nil)
Может этот метод лучше обозвать `build` или `create`?..

2017-06-29 10:25 UTC, zverok commented on movie.rb
> +    end
Кстати, всю эту штуку можно очень круто упростить, если сначала привести и фильтр, и значение к массиву (есть такой метод `Array()`, который одиночное значение оборачивает в массив, а переданный массив просто возвращает как есть). Ни одного `if`-а не понадобится ;)

2017-06-29 10:25 UTC, zverok commented on spec/movie_collection_spec.rb
> +      it { is_expected.to eq(collection.all.sort_by(&:length)) }
Что-что здесь происходит?.. Пустой контекст, проверка сортировки по длине, зачем-то перебираются все поля?..

2017-06-29 10:25 UTC, zverok commented on spec/movie_collection_spec.rb
> +      it { is_expected.to all have_attributes(director: 'Fedor Bondarchuk') }
а этот тест тут зачем, если оно `empty`? :)

2017-06-29 10:25 UTC, zverok commented on spec/spec_helper.rb
> +require 'date'
А эти два зачем? Твой код их и так require

2017-06-29 10:25 UTC, zverok commented on spec/theatre_spec.rb
> +      }
↑ этот комментарий всё ещё в силе.

2017-06-29 10:25 UTC, zverok commented on theatre.rb
> +    mov = filter(PERIOD[time]).select { |movie| movie.rating * rand }.last
а что здесь `select` делает?..

2017-07-06 14:08 UTC, zverok approved these changes
Замечания поправь-то перед мерджем. Но всё хорошо!

2017-07-06 14:08 UTC, zverok commented on movie_collection.rb
> +  def show_movie(movie)
Учитывая, что его используют только наследники, приватное ж пусть будет?

2017-07-06 14:08 UTC, zverok commented on netflix.rb
> +  def select_movie(params)
приватный же? да и можно теперь не делать его отдельным методом, в `show` засунуть, две строчки ж всего.

2017-07-06 14:08 UTC, zverok commented on theatre.rb
> +  end
тоже по-моему можно слить обратно с `show`

2017-07-06 16:32 UTC, Hunk13 commented on theatre.rb
> +  end
Оставлю как приватные методы. "В идеале каждый метод делает одну вещь." &copy;

2017-07-06 16:33 UTC, merged